CREATE TABLE transactions (
id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
teamOutId       INT,
teamOutName     VARCHAR,
teamInId        INT,
teamInName      VARCHAR,
playerName      VARCHAR NOT NULL,
transferDate    VARCHAR NOT NULL,
transferType    VARCHAR
);
